"""Export pipeline as YAML and as executable Python code."""

from __future__ import annotations

from typing import Any

import yaml  # type: ignore[import-untyped]


def _spec_to_python_literal(obj: Any) -> str:
    """Convert pipeline spec to a valid Python literal string (repr for basic types)."""
    if obj is None:
        return "None"
    if isinstance(obj, bool):
        return "True" if obj else "False"
    if isinstance(obj, (int, float)):
        return repr(obj)
    if isinstance(obj, str):
        return repr(obj)
    if isinstance(obj, (list, tuple)):
        parts = ", ".join(_spec_to_python_literal(x) for x in obj)
        return "[" + parts + "]"
    if isinstance(obj, dict):
        parts = ", ".join(f"{repr(k)}: {_spec_to_python_literal(v)}" for k, v in obj.items())
        return "{" + parts + "}"
    return repr(obj)


def pipeline_to_yaml(pipeline_spec: dict[str, Any]) -> str:
    """Serialize pipeline_spec to a YAML string."""
    if not isinstance(pipeline_spec, dict):
        raise ValueError("pipeline_spec must be a dict.")
    # Ensure version if missing
    out = dict(pipeline_spec)
    if "version" not in out:
        out["version"] = 1
    return yaml.dump(out, default_flow_style=False, sort_keys=False, allow_unicode=True)


def pipeline_to_python(
    pipeline_spec: dict[str, Any],
    *,
    input_path: str = "input.csv",
    output_path: str = "output.csv",
) -> str:
    """
    Generate Python code that loads a CSV, applies the pipeline, and saves the result.

    Includes a placeholder for the input path. The pipeline spec is embedded and
    apply_pipeline is called.
    """
    if not isinstance(pipeline_spec, dict):
        raise ValueError("pipeline_spec must be a dict.")

    spec_literal = _spec_to_python_literal(pipeline_spec)

    return f'''"""
Reproducible pipeline generated by TidyWizard.
Run from project root: python pipeline.py
"""

import pandas as pd

# Adjust paths as needed
INPUT_PATH = "{input_path}"
OUTPUT_PATH = "{output_path}"

PIPELINE_SPEC = {spec_literal}


def main() -> None:
    df = pd.read_csv(INPUT_PATH, dtype_backend="numpy_nullable")
    from core.pipeline import apply_pipeline

    df_clean = apply_pipeline(df, PIPELINE_SPEC)
    df_clean.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved {{len(df_clean)}} rows to {{OUTPUT_PATH}}")


if __name__ == "__main__":
    main()
'''
